plugin:
    has_options: false
    
    resources:
        -   class: Mindmecn\MarkdownBundle\Entity\Markdown
            name: markdown
            tags: [content,lab]
 #           is_exportable: true
            icon: markdown.png
  
        -   class: Mindmecn\MarkdownBundle\Entity\Mkppt
            name: mkppt
            tags: [content,lab]
 #           is_exportable: false
            icon: mkppt.png
            actions:
              - name: slide
                decoder: slide
                group: management
                api: [get]
            
        -   class: Mindmecn\MarkdownBundle\Entity\Mknote
            name: mknote
            tags: [content,lab]
#            is_exportable: false
            icon: mknote.png
            
        -   class: Mindmecn\MarkdownBundle\Entity\Mklab
            name: mklab
            tags: [content,lab]
#            is_exportable: false
            icon: mklab.png
            
        -   class: Mindmecn\MarkdownBundle\Entity\Mktemplate
            name: Mktemplate
            tags: [content,lab]
#            is_exportable: false
            icon: mktemplate.png